version: '3'
services:
  mysql:
    build: ./mysql-docker
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: mysql
    ports:
      - "3333:3306"
  express:
    build: ./express-docker
    restart: always
    container_name: express
  nginx:
    build: ./nginx-docker
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"