version: '3'
services:
  mysql:
    build: ./mysql-docker
    restart: always
    container_name: mysql
    ports:
      - "3333:3306"
  express:
    build: ./express-docker
    restart: always
    container_name: express
  nginx:
    build: ./nginx-docker
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"