FROM nginx:latest
RUN apt update
RUN apt install -y git
COPY default.conf /etc/nginx/conf.d/default.conf
COPY test.won-one.com-key.pem /etc/nginx/ssl/
COPY test.won-one.com.pem /etc/nginx/ssl/
RUN mkdir /home/web
WORKDIR /home
ENTRYPOINT rm -r web && mkdir web && git clone https://github.com/pleroma1112/web-react-app.git web && service nginx start && tail -f /dev/null